name: Push to Hugging Face

on:
  push:
    branches: [huggingface-space]
  workflow_dispatch:

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://damand2061:$HF_TOKEN@huggingface.co/spaces/damand2061/flow-chat huggingface-space:main
